feat: configuração inicial do banco de dados. #1
SuperJrs/money-mastery-fastapi-oaph pull request #2
Opened 2023-03-02 22:41 UTC by ozielhumasi

Configurações iniciais do banco de dados feita.

2023-03-03 19:54 UTC, LamequeFernandes requested changes
Muito bom, mas é importante adicionar uma "camada" responsável pelas interações com o banco de dados(repository), dessa forma as controllers ficaram mais "limpas".
Além disto, busque realizar commits "atômicos".

2023-03-08 21:26 UTC, LamequeFernandes requested changes
Muito bom, só retirar o print e ta pronto.

2023-03-08 21:26 UTC, LamequeFernandes commented on controllers/conta.py
> +    print(result)
Retirar print para manter o código "mais limpo"

2023-03-09 21:02 UTC, ozielhumasi commented
Correções realizadas.
O print foi removido.

2023-03-09 21:02 UTC, LamequeFernandes approved these changes

2023-03-09 21:02 UTC, merged